// Generated by Wrangler on Tue Apr 09 2024 14:53:23 GMT+0000 (Coordinated Universal Time)
// by running `wrangler types`

interface Env {
	SEND_API_KEY: string;
	LOG_DATA: D1Database;
	MAIN_DATA: D1Database;
	MAIN_DB: D1Database;
}
