// Generated by Wrangler on Fri Apr 05 2024 16:49:34 GMT+0000 (Coordinated Universal Time)
// by running `wrangler types`

interface Env {
	SEND_API_KEY: string;
	LOG_DATA: D1Database;
	MAIN_DATA: D1Database;
}
